### ISSUE TITLE
Command ‘argon.openMenu’ not found

### ISSUE THREAD

**Issue by lucastoledo95** [argon-rbx/argon-vscode#17] opened 2024-07-06 05:12 UTC
It is necessary to update the plugin in visual studio code, when trying to open the plugin it gives an error in the "Open menu" command

**Comment by DervexDev** [comment] 2024-07-06 09:21
This is a known issue and currently, there is no way to fix it as it is extremely random. It only occurs for some users and I cannot reproduce this on any of my 3 machines (macOS, Windows & Linux).

You can try running VS Code as an administrator because this is what fixes the issue for most users.

**Comment by DervexDev** [comment] 2024-07-16 16:09
I'm gonna reopen this issue so that others can see that it's a known problem and find a possible solution.

**Comment by Overseer-Programmer** [comment] 2024-07-31 12:38
For me the issue was that the server part of Argon was not being installed when installing the Argon extension on vscode, which caused the extension to error during startup. Installing the server part of argon separately fixed the problem.

**Comment by DervexDev** [comment] 2024-08-09 02:15
@Overseer-Programmer in version [2.0.9](https://github.com/argon-rbx/argon-vscode/releases/tag/2.0.9) Argon now displays what exactly happened when a critical error occurs. Could you temporarily move your manual Argon installation somewhere else and send me the new error message you should get when running `Argon: Open Menu`?

**Comment by Overseer-Programmer** [comment] 2024-08-09 09:43
I uninstalled the vscode extension and the argon server and when reinstalling the extension the argon server was also successfully installed alongside it. I no longer get an error when running `Argon: Open Menu` and the extension works as expected. However, i do get this error every time the argon extension is activated:

![Screenshot from 2024-08-09 11-40-55](https://github.com/user-attachments/assets/0ea0abd2-c1c0-458d-8b06-7886216b65f3)

**Comment by Overseer-Programmer** [comment] 2024-08-10 08:04
My os is: Zorin OS 17.1 Core (Linux distro)
My os type is:  64-bit
My CPU is: Intel® Core™ i7-9700K CPU @ 3.60GHz × 8

**Comment by DervexDev** [comment] 2024-08-10 18:47
Just run `argon config install_plugin false` in your terminal. It disables automatic Roblox Studio plugin updates as Argon does it by default; currently, this feature is not available on Linux.

**Comment by Aristosis** [comment] 2024-08-25 14:19
I can confirm this is a **persistent** issue, I just didn't report it because it somehow got fixed and I figured it was an issue with the way i installed it.
Disabling `install_plugin` in the global config and then removing the manually installed argon from `~/.argon` (I install argon via aftman, and `~/.aftman/bin/` is in `$PATH`), the plugin will simply install argon again, and if provided a custom path to the aftman binary directory, it stops working.

**Comment by DervexDev** [comment] 2024-08-26 10:42
Thanks for these details, they are very helpful. I will look into that and hopefully fix it once I have more time.

**Comment by DervexDev** [comment] 2024-09-09 20:59
Hey @Aristosis can you verify if [this test build](https://github.com/user-attachments/files/16936536/argon-2.0.13.vsix.zip) fixes the issue for you?

**Comment by Aristosis** [comment] 2024-09-15 11:15
> Hey @Aristosis could you verify whether this [test build](https://github.com/user-attachments/files/16936536/argon-2.0.13.vsix.zip) or version [2.0.13](https://github.com/argon-rbx/argon-vscode/releases/tag/2.0.13) fixes the issue for you?
> 

Hi! Sorry for the late reply, I actually don't have access to my PC till a week from now. I'll check it out once I get the chance and put a comment on this issue

**Comment by Aristosis** [comment] 2024-09-29 07:28
It works. again might be a fluke cause the nature of the problem is like that but so far its been ok every time I tested

**Comment by DervexDev** [comment] 2024-10-02 16:20
Okay great, I will close the issue for now but feel free to reopen it if needed.

**Closed by DervexDev** 2024-10-02 16:20 UTC
Labels: bug, help wanted
